### ISSUE TITLE
Audio files are not being trimmed correctly

### ISSUE THREAD

**Issue by mcartwright** [justinsalamon/scaper#10]
When I generate audio files from a jams files, the jams file metadata says the duration should be 10 seconds, but the generated audio is 12 seconds. I haven't investigated this much, but it seems like this may be due to the padding that sox uses when applying reverb.

**Comment by justinsalamon** [comment]
This was because the function was using the duration value stored in the annotation's sandbox.scaper['duration'] field, which was being updated when calling scaper.trim (bug).

Fixed by 5bc375daeb649ef6acf7ea793dee11928b505e2f.
