### ISSUE TITLE
Bug in `generate_from_jams` when `save_isolated_events` is True, and a `trim` operation was called prior to generating.

### ISSUE THREAD

**Issue by pseeth** [justinsalamon/scaper#113]
Through some happenstance, I noticed that this will happen here:

https://github.com/justinsalamon/scaper/blob/33def127bf17cdec3858b868538ee4ea41bd0dde/scaper/core.py#L181-L196

Should be easy to fix. `audio_outfile` should be `audio_file` here. I'll make a test, get it to fail, then issue a fix in a PR.

**Comment by justinsalamon** [comment]
Fixed via #115
