### ISSUE TITLE
scaper.scaper_exceptions.ScaperError: Label value must match one of the available labels: []

### ISSUE THREAD

**Issue by CleanPegasus** [justinsalamon/scaper#141]
I'm getting the following error on trying to merge .wav files from 2 different folders.

**Comment by justinsalamon** [comment]
I need more information to be able to help resolve this issue. Please provide a minimal working example for the code that generated this error. Please also specify:
* Your source folder structure and contents (foreground and background)
* Scaper version, Python version, and operating system

Thanks
