### ISSUE TITLE
support jams 0.3

### ISSUE THREAD

**Issue by bmcfee** [justinsalamon/scaper#21]

**Comment by justinsalamon** [comment]
haha yeah, that's basically what scaper 2.0 will be about.

**Comment by bmcfee** [comment]
reupping this -- trying to load urbansed data fails without the scaper package installed, because it does not include the namespace def.  Following the recommendations to install scaper clobbered my jams install, and trying to fix it has really wrecked up my conda environment. :cry:

**Comment by justinsalamon** [comment]
yikes! Probably the best solution is to provide the [sound_event namespace](https://github.com/justinsalamon/scaper/blob/master/scaper/namespaces/sound_event.json) with the URBAN-SED dataset. I'll look into that.

**Comment by justinsalamon** [comment]
Closed via #31
