### ISSUE TITLE
Try scaper v1.0.0rc1

### ISSUE THREAD

**Issue by justinsalamon** [justinsalamon/scaper#34]
Hello!

I've just pushed scaper v1.0.0rc1 to pypi: `pip install scaper==1.0.0rc1`

This major update supports jams>=0.3.2, uses the `scaper` namespace instead of `sound_event`, and drops the dependency on pandas.

@lostanlen @Elizabeth-12324 @bmcfee @pseeth if you have the time it'd be great if you could give this pre-release a quick whirl and let me know if there are any issues before I push v1.0.0 out. Ideally I'd like to release the formal v1.0.0 within a week from today.

Things to note:
* Requires the latest jams release (0.3.2) due to the use of the new `scaper` namespace.
* The change in namespace means you won't be able to load jams files created with earlier versions of scaper. An easy fix is to manually edit the jams file replacing the value of the namespace field from `sound_event` to `scaper`. The file should then load fine.
* For windows users: if you install this RC in a fresh environment note you'll have to manually install pysox v1.3.4 since it hasn't yet been released on pypi: pinging @rabitt

Any/all feedback is welcome.

Cheers!!

**Comment by Elizabeth-12324** [comment]
So far everything is working and no issues have occurred, scaper still functions as before.

**Comment by justinsalamon** [comment]
Awesome, thanks @Elizabeth-12324 for reporting back!

**Comment by lostanlen** [comment]
@Elizabeth-12324 will use scaper v1.0.0-rc1 a bit more tomorrow and Friday. If everything keeps going well, I think that we can stick to your plan of releasing v1.0.0 next Monday

**Comment by justinsalamon** [comment]
Excellent, if I don't hear back from either of you with any issues I'll release v1.0.0 on Monday. Thanks @Elizabeth-12324 and @lostanlen !

**Comment by justinsalamon** [comment]
Just released v1.0.0 on pip, closing.
