### ISSUE TITLE
generate_from_jams doesn't respect custom sample rates

### ISSUE THREAD

**Issue by bensteers** [justinsalamon/scaper#39]
It looks to be an easy fix. I can submit a PR when I get a minute.

https://github.com/justinsalamon/scaper/blob/634ea13e5c8d8f66b70414a4e19d2479c0adee0a/scaper/core.py#L133
https://github.com/justinsalamon/scaper/blob/634ea13e5c8d8f66b70414a4e19d2479c0adee0a/scaper/core.py#L1397

**Comment by justinsalamon** [comment]
Ah yes, I forgot to save `self.sr` in the sandbox (line 1397), and then forgot to load it into `self.sr` in `generate_from_jams`. Nice catch!

Happy to accept a PR, please note it should include not only the fix to the code, but also the necessary unit test(s) to ensure 100% test coverage is maintained. Thanks!

**Comment by justinsalamon** [comment]
p.s - the PR should also include a version bump to 1.0.1 (short version stays on 1.0) :)
