### ISSUE TITLE
Output each source (label) to a separate audio track to support source sep train/eval

### ISSUE THREAD

**Issue by beasteers** [justinsalamon/scaper#42]
`generate_from_jams` should have an option to generate audio separated by label for training source separation algs. You can probably just hack it by filtering the scaper jams files, so it isn't anything urgent, but I think it would be a valuable feature to add at some point.

**Comment by pseeth** [comment]
Hey Ben, I actually have a fork that does this:

https://github.com/pseeth/scaper/tree/source_separation

However, it's out of date with current master and needs some work in terms of documentation and test cases and merging with current master.

**Comment by bensteers** [comment]
Oh cool. It had just occurred to me during the MARL/MIR presentation today that it wasn't an option so I thought I'd point it out, but glad to see someone started work on it already.

**Comment by justinsalamon** [comment]
Yes, this feature has been in the pipeline for while. Note that it's a general feature and not specifically tied to the `generate_from_jams` function (one might to directly output to separate audio files).

@pseeth how's that coming along? ;)

**Comment by pseeth** [comment]
@justinsalamon, it's done!
