### ISSUE TITLE
Soundscape generation getting slower after every iteration

### ISSUE THREAD

**Issue by grand3110** [justinsalamon/scaper#67]
Hi, 

I'm trying to generate 1000 soundscapes use scaper but I realized that while running my code, after each iteration, the generation of soundscapes gets slower. For example: after generating 100 soundscapes, the 101th took almost 1 min, whereas for first few soundscapes it only took around 2 seconds. This increase in time is gradual and I can't figure out a root cause to it. 

Please help. The code I'm using is below:

````
# Generate n soundscapes
for i in range(n_start, n_stop):
    print('Generating soundscape: {:d}/{:d}'.format(i+1, n_soundscapes))
    # add random number of foreground events
    n_events = np.random.randint(1, 5)
    
    for _ in range(n_events):
        event_time = np.random.randint(0, duration)
        event_duration = duration - event_time
        sc.add_event(label = ("const", "chainsaw"),
                     source_file = ("choose", []),
                     source_time = ("uniform", 0, 30 - duration),
                     event_time = ("uniform", 0, event_time),
                     event_duration = ("uniform", 1, event_duration),
                     snr = ("uniform", -5, 0),
                     pitch_shift = ("uniform", -15, 15),
                     time_stretch = None)
    
    audiofile = outfolder + f'soundscape_{i}.wav'
    jamsfile = jamsfolder + f'soundscape_{i}.jams'
    txtfile = txtfolder + f'soundscape_{i}.txt'
    
    sc.generate(audiofile, jamsfile,
                allow_repeated_label = True,
                allow_repeated_source = True,
                disable_sox_warnings = True,
                no_audio = False,
                txt_sep = ',',
                txt_path = txtfile)

```

**Comment by grand3110** [comment]
I finally figured out how to solve this issue. I need to create the scaper object within the loop. But I'm not sure why it should be this way. 

Can somebody please explain this to me?
Here is my updated code which I realize is the code on the read me files of scaper:

```
# Generate n soundscapes
for i in range(n_start, n_stop):
    print('Generating soundscape: {:d}/{:d}'.format(i+1, n_soundscapes))
    
    # create a scaper
    sc = scaper.Scaper(duration, fg_folder, bg_folder)
    sc.protected_labels = []
    sc.ref_db = 0

    # Add background
    sc.add_background(label = ("const", "rainforest_day"),
                     source_file = ("choose", []),
                     source_time = ("uniform", 0, 30 - duration))
    
    # add random number of foreground events
    n_events = np.random.randint(1, 5)
    
    for _ in range(n_events):
        event_time = np.random.randint(0, duration)
        event_duration = duration - event_time
        sc.add_event(label = ("const", "chainsaw"),
                     source_file = ("choose", []),
                     source_time = ("uniform", 0, 30 - duration),
                     event_time = ("uniform", 0, event_time),
                     event_duration = ("uniform", 1, event_duration),
                     snr = ("uniform", -5, 0),
                     pitch_shift = ("uniform", -15, 15),
                     time_stretch = None)
    
    audiofile = outfolder + f'soundscape_{i}.wav'
    jamsfile = jamsfolder + f'soundscape_{i}.jams'
    txtfile = txtfolder + f'soundscape_{i}.txt'
    
    sc.generate(audiofile, jamsfile,
                allow_repeated_label = True,
                allow_repeated_source = True,
                disable_sox_warnings = True,
                no_audio = False,
                txt_sep = ',',
                txt_path = txtfile) 
```

**Comment by justinsalamon** [comment]
Here's what's happening: a scaper object has state. This means that when you add events to the scaper object's specification (via add_background or add_event), these events are stored. If you only create one scaper object outside the loop, then in each iteration of the loop you're adding more and more events to the *same* specification, so basically you're specification is getting longer and longer, and each generated soundscape will have 5 more events compared to the previously generated one, which is not what you're after I believe. So, in this scenario, while your first generated soundscape had between 1-5 events, the 100'th soundscape will have between 100-500 events, and the 1000's soundscape between 1000-5000 events.

By creating a new scaper object in each iteration of the loop, you're resetting the event specification, and hence clearing out previously added events and ensuring you only have between 1-5 events as desired. Note that in the example provided in the README file and in the tutorial, the scaper object is inside the loop, as it should be.
