### ISSUE TITLE
Function to reset the event specification in the Scaper object

### ISSUE THREAD

**Issue by pseeth** [justinsalamon/scaper#69]
It might be useful to have a way to reset the event specification in a Scaper object so that the same Scaper object can be used over and over to generate soundscapes, instead of making a Scaper object inside the loop for each soundscape like in the tutorial.

Current proposal is to add a function to the Scaper object called `Scaper.reset_event_spec()` which would accomplish this. Looking through `Scaper._instantiate`, the only objects that get touched that belong to `self` are `self.bg_spec` and `self.fg_spec`. As these are both lists, I think the body of `reset_event_spec` would look something like:

```
def reset_event_spec(self):
  self.fg_spec = []
  self.bg_spec = []
```

Which are their original settings in the init function.

We would need a corresponding test. Maybe generate something, then reset the object, then generate again? And make sure the generated soundscapes are different from one another?

**Comment by justinsalamon** [comment]
Yes, let's add this! A few comments:
* `Scaper._instantiate()` also touches `self.duration`. It also calls `self._instantiate_event()` which touches `self.bg_path`, `self.fg_path`, `self.bg_labels`, `self.fg_labels`, `self.protected_labels` and `self.duration`. Then there's `_generate_audio()` which touches pretty much all other parameters in `self.*`. All this to say, there's a big difference between the notion of resetting the Scaper object and just resetting the event specifications, and we should limit ourselves to the latter in this context.
* It occurred to me that there's a valid (and common) use case for wanting to only reset either the foreground or background spec, for example when you want the same background but different foreground events, and vice versa (e.g. for model evaluation ablations). So how about we break this down into `reset_fg_event_spec()` and `reset_bg_evet_spec()`?
* The implementation, as you've noted, is trivial. Where I think we need to spend time/effort is in documenting the behavior of these functions in docstrings, as well as explaining and demonstrating with examples in the documentation how to use them.
* In terms of tests, the trivial ones to add are to check that the lists have been set to empty lists. Next, we can create a Scaper object and add events to it and then reset the specs, and compare it to another objects that hasn't had events added to it, and they should be identical. Finally, we could have a test that creates a Scaper object, adds events to it and instantiates a JAMS file. Then we reset the event specs, start it off with the same seed again, repeat the process and instantiate another JAMS. The two JAMS files should be identical.
* This just made me thing: in additional to providing a random seed as part of the init function, do we also want to add a function `Scaper.set_random_seed()` in case someone wants to change the random seed of an already existing Scaper object?

How does this all sound?

**Comment by pseeth** [comment]
All sounds good. I'll fold this into #54!

**Comment by justinsalamon** [comment]
Added via #54
