### ISSUE TITLE
namespaces not included in setup

### ISSUE THREAD

**Issue by mcartwright** [justinsalamon/scaper#8]
If you install with setup.py, the namespaces are not included with the installation, preventing a user from being able to import the scaper module.

**Comment by justinsalamon** [comment]
@mcartwright I just made some changes that (in theory) should fix this. Could you pull the latest version of the code and give it another try?

**Comment by mcartwright** [comment]
I was able to import it after installing it without error.

**Comment by justinsalamon** [comment]
Awesome, thanks!
