### ISSUE TITLE
Output audio format should match input format

### ISSUE THREAD

**Issue by justinsalamon** [justinsalamon/scaper#87]
From @epicycles and @haerdogan:

Scaper used to make outputs in the same format (e.g., float32 vs int16) as the audio input, but since #55 was merged it is always outputting int16, regardless of the input.   

@haerdogan traced this down to the code that fixes sox off-by-one errors, and wrote a pull request to handle this (the currently closed without merge #86).  

@pseeth will create a PR for this based on @haerdogan's proposed solution in #86.

**Comment by haerdogan** [comment]
Yeah, feel free to copy something from my fork if it helps. I have not tested it well enough and it may cause some issues.

**Comment by justinsalamon** [comment]
Fixed via #88
